name: antefoyer 
channels:
  - conda-forge
dependencies:
  - foyer >=0.12.0
  - ambertools
  - networkx
  - pip
  - python >=3.9, <3.13
  - pip:
      - git+https://github.com/chrisjonesBSU/antefoyer.git@main 
